name: package-manager-ci

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    permissions:
      contents: read
    uses: fastify/workflows/.github/workflows/plugins-ci-package-manager.yml@v6
